name: Create issue

on:
  workflow_dispatch:

  schedule:
    - cron:  '0 20 * * *'

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create learn together issue action
        uses: developer-plus/learn-together-action@main
        with:
          token: ${{secrets.TOKEN}}
